import type { ReactElement } from "react";

export const intro: ReactElement = (
  <>
    <p>
      Diffing JSON sounds easy — just run a text diff. But JSON is
      structured, not lines, so a text diff flags formatting changes
      and key reorderings as real differences when they aren&rsquo;t.
      A proper JSON diff understands objects (order-independent),
      arrays (order-dependent), and types. This guide covers how JSON
      diffing works, the gotchas around array matching, numeric
      precision, missing-vs-null, when text diff is actually the
      right tool, and how to use diffs in code review, API contract
      testing, and debugging.
    </p>
  </>
);

export const body: ReactElement = (
  <>
    <h2>Why text diff fails on JSON</h2>
    <p>
      Given these two JSON values:
    </p>
    <pre>
{`{ "a": 1, "b": 2 }
{ "b": 2, "a": 1 }`}
    </pre>
    <p>
      A text diff says they&rsquo;re different. A JSON diff says
      they&rsquo;re identical. Object key order is not semantic in
      JSON.
    </p>
    <p>
      Same for formatting — <code>{`{"a":1}`}</code> and{" "}
      <code>{`{ "a": 1 }`}</code> are identical. And trailing
      newlines, indentation, whitespace inside strings (actually
      that&rsquo;s semantic — careful).
    </p>

    <h2>Structural diff basics</h2>
    <p>
      A JSON diff walks the tree recursively and reports changes in
      semantic terms:
    </p>
    <p>
      <strong>Added:</strong> key present in new, not in old.
    </p>
    <p>
      <strong>Removed:</strong> key present in old, not in new.
    </p>
    <p>
      <strong>Changed:</strong> key in both, values different.
    </p>
    <p>
      <strong>Unchanged:</strong> key in both, values identical.
    </p>
    <p>
      For nested structures, drill into the object/array recursively
      and report paths like <code>user.address.city</code> instead of
      line numbers.
    </p>

    <h2>Array diffing is hard</h2>
    <p>
      Object keys are unique; array positions aren&rsquo;t. If
      you&rsquo;ve got:
    </p>
    <pre>
{`old: [{ "id": 1 }, { "id": 2 }, { "id": 3 }]
new: [{ "id": 2 }, { "id": 3 }]`}
    </pre>
    <p>
      Did position 0 change from <code>{`{id:1}`}</code> to{" "}
      <code>{`{id:2}`}</code>, and position 2 get removed? Or did
      position 0 get removed entirely?
    </p>
    <p>
      <strong>Positional matching:</strong> compare by index. Simple,
      but sensitive to insertions.
    </p>
    <p>
      <strong>Keyed matching:</strong> tell the differ to match by
      a specific field (e.g., <code>id</code>). Matches{" "}
      <code>{`{id:2}`}</code> to the same <code>{`{id:2}`}</code>
      {" "}regardless of position.
    </p>
    <p>
      <strong>LCS (longest common subsequence):</strong> treat array
      like text; find the best edit sequence. Good for ordered lists.
    </p>
    <p>
      Picking the right strategy depends on what the array
      represents. Tell the tool which field is the identity, and it
      does the right thing.
    </p>

    <h2>Numeric precision gotchas</h2>
    <p>
      JSON numbers don&rsquo;t carry type info. Is <code>1</code>
      {" "}the same as <code>1.0</code>? Most tools say yes. Is
      {" "}<code>0.1 + 0.2</code> equal to <code>0.3</code>? Your
      language says{" "}<code>0.30000000000000004</code>, so maybe no.
    </p>
    <p>
      <strong>When comparing numbers,</strong> use epsilon tolerance
      for floats generated by computation. Exact match only for
      integers and hand-typed decimals.
    </p>
    <p>
      <strong>Beware JSON number overflow:</strong> JS parses
      {" "}<code>9007199254740993</code> as{" "}<code>9007199254740992</code>
      {" "}(loses a bit). If your data has IDs above 2^53, use
      strings for them — and configure your differ to treat{" "}
      <code>&quot;12345&quot;</code> and <code>12345</code> as
      different.
    </p>

    <h2>Missing vs null vs undefined</h2>
    <p>
      JSON has <code>null</code> but no <code>undefined</code>. A
      key being absent is different from a key being present with
      value <code>null</code>:
    </p>
    <pre>
{`{ "a": null }   vs   {}`}
    </pre>
    <p>
      Some APIs treat these identically; some don&rsquo;t. Your
      diff tool needs a consistent stance:
    </p>
    <p>
      <strong>Strict:</strong> missing and null are different. Safer
      for contract testing.
    </p>
    <p>
      <strong>Loose:</strong> missing and null are the same. Useful
      for comparing API responses where optional fields drop out.
    </p>

    <h2>Viewing the diff</h2>
    <p>
      <strong>Side-by-side:</strong> old on left, new on right, with
      changes highlighted. Best for small objects.
    </p>
    <p>
      <strong>Unified (path-based):</strong> list of changes by JSON
      path:{" "}
      <code>~user.email: &quot;old@x&quot; -&gt; &quot;new@x&quot;</code>.
      Compact for large objects with few changes.
    </p>
    <p>
      <strong>JSON Patch (RFC 6902):</strong> structured output of
      operations:{" "}
      <code>{`[{"op": "replace", "path": "/user/email", "value": "new@x"}]`}</code>.
      Machine-readable; can be applied to the old object to produce
      the new.
    </p>
    <p>
      <strong>JSON Merge Patch (RFC 7396):</strong> simpler format
      where the patch is just a partial JSON object. Can&rsquo;t
      represent array operations well; good for simple object
      updates.
    </p>

    <h2>Common use cases</h2>
    <p>
      <strong>API contract testing:</strong> hit a known endpoint,
      compare response against a snapshot. Alerts when schema drifts.
    </p>
    <p>
      <strong>Config file review:</strong> compare two config versions
      to see what changed. Much cleaner than git diff on formatted
      YAML/JSON.
    </p>
    <p>
      <strong>Sync debugging:</strong> compare source and target of a
      sync to find what&rsquo;s missing or malformed.
    </p>
    <p>
      <strong>State snapshots in tests:</strong> Jest&rsquo;s{" "}
      <code>toMatchSnapshot</code> does a text diff; a JSON diff is
      cleaner for structured state.
    </p>

    <h2>When to use text diff instead</h2>
    <p>
      <strong>Formatting matters:</strong> checking whether a JSON
      file&rsquo;s indentation changed — text diff.
    </p>
    <p>
      <strong>Comments in JSON5/JSONC:</strong> JSON diff tools strip
      comments; text diff preserves them.
    </p>
    <p>
      <strong>Version control:</strong> git diff on JSON files.
      Ugly, but already integrated. For PR review, a structural diff
      add-on (like Gitiles&rsquo; json-diff) is nicer.
    </p>

    <h2>Common mistakes</h2>
    <p>
      <strong>Diffing JSON as text.</strong> Formatting noise buries
      real changes. Use structural diff.
    </p>
    <p>
      <strong>Ignoring array-order semantics.</strong> If order
      doesn&rsquo;t matter (e.g., tags), tell the diff. If it does
      matter (e.g., steps in a workflow), keep positional diff.
    </p>
    <p>
      <strong>Treating null and missing as same.</strong> APIs
      distinguish them. Your contract test should too.
    </p>
    <p>
      <strong>Comparing pretty-printed JSON.</strong> If one side is
      minified and the other is pretty-printed, text diff shows every
      line as changed. Normalize format first.
    </p>
    <p>
      <strong>Exact-match floats.</strong> Computed floats rarely
      match byte-exactly. Use tolerance.
    </p>

    <h2>Run the numbers</h2>
    <p>
      Compare JSON structures instantly with the{" "}
      <a href="/tools/json-diff-checker">JSON diff checker</a>. Pair
      with the{" "}
      <a href="/tools/json-formatter">JSON formatter</a> to normalize
      before diffing, and the{" "}
      <a href="/tools/diff-checker">text diff checker</a> when you
      need a plain line diff.
    </p>
  </>
);
