/* eslint-disable react/no-unescaped-entities */

export const intro = (
  <>
    <p>
      &ldquo;How do I convert PDF to Word in 30 seconds?&rdquo; is the most
      asked PDF question on Reddit. The honest answer: there are three
      paths depending on the PDF you have, and only one of them is the
      30-second one. This guide walks you through each, so you pick the
      right tool the first time.
    </p>
  </>
);

export const toc = [
  { id: "fast-path", label: "The 30-second path (text-based PDFs)" },
  { id: "scanned", label: "Scanned + handwritten PDFs (OCR required)" },
  { id: "complex", label: "Complex layouts (tables, multi-column)" },
  { id: "editable", label: "Making PDF text editable" },
  { id: "tools", label: "Recommended tools per scenario" },
];

export const body = (
  <>
    <h2 id="fast-path">The 30-second path: PDF to Word for text-based PDFs</h2>
    <p>
      If your PDF was created from a Word document, exported from a web page, or
      generated by software, the text is already selectable. You can verify by
      opening the PDF and trying to highlight a paragraph — if the highlight
      sticks, it&rsquo;s text-based.
    </p>
    <p>
      Three options, all under 30 seconds:
    </p>
    <ol>
      <li>
        <strong>Microsoft Word (already on your machine).</strong> File → Open →
        select the PDF. Word converts it to an editable document on the spot.
        Layout fidelity: 80–95% for simple PDFs, lower for complex layouts.
      </li>
      <li>
        <strong>Google Docs.</strong> Upload the PDF to Drive, right-click →
        Open with Google Docs. Same idea as Word, comparable fidelity. Free.
      </li>
      <li>
        <strong>Browser-only text extraction.</strong> Use our{" "}
        <a href="/tools/pdf-to-text">PDF to text tool</a> to extract the text,
        then paste into Word/Docs. Loses formatting but the privacy upside is
        significant — no upload, no cloud round-trip.
      </li>
    </ol>
    <p>
      For most users the Word/Docs path is fastest. For sensitive documents
      (legal, financial, medical), the browser-only path keeps your file local.
    </p>

    <h2 id="scanned">Scanned + handwritten PDFs (OCR required)</h2>
    <p>
      A scanned PDF is just images of text bound into a PDF wrapper. Word and
      Docs can&rsquo;t convert those without OCR (optical character recognition)
      first. Symptoms: you can&rsquo;t select text, copy-paste comes out blank
      or garbled.
    </p>
    <p>
      Free OCR options:
    </p>
    <ul>
      <li>
        <strong>Our <a href="/tools/pdf-ocr-to-text">PDF OCR tool</a>.</strong>{" "}
        Browser-side OCR using Tesseract.js. Works for English, Spanish, French,
        German, Portuguese, Italian. Print + clean handwriting hits 85–95%
        accuracy. Slower than cloud OCR (5–15s per page) but private.
      </li>
      <li>
        <strong>Adobe Acrobat Pro.</strong> Built-in OCR is high quality. $20/month.
        Worth it if you do this daily.
      </li>
      <li>
        <strong>Google Drive.</strong> Upload PDF, right-click → Open with Google
        Docs. Drive automatically OCRs scanned PDFs. Quality is decent. File goes
        through Google&rsquo;s servers — privacy tradeoff.
      </li>
      <li>
        <strong>ABBYY FineReader.</strong> Best-in-class OCR accuracy, especially
        on tables and complex layouts. $200 one-time or subscription. Pro tool.
      </li>
    </ul>
    <p>
      For handwriting specifically, accuracy varies wildly. Print handwriting
      and clear cursive: 70–90%. Messy / personal-shorthand cursive: 30–60%.
      You&rsquo;ll still need to proofread.
    </p>

    <h2 id="complex">Complex layouts: tables, multi-column, scientific</h2>
    <p>
      The free tools above struggle with:
    </p>
    <ul>
      <li>
        <strong>Tables:</strong> often output as space-separated text, losing
        structure. Workarounds: ABBYY FineReader (paid), or manual cleanup in a
        spreadsheet after extraction.
      </li>
      <li>
        <strong>Multi-column layouts:</strong> often interleaved into one
        column. Workaround: extract column-by-column manually if there are only
        2–3 columns; pay for ABBYY for many.
      </li>
      <li>
        <strong>Scientific papers with math symbols:</strong> the LaTeX-rendered
        equations come out as garbled characters in plain text. Conversion to
        EPUB or DOCX preserves the rendered images, but you can&rsquo;t edit the
        equations. See our{" "}
        <a href="/guides/ebook-and-3d-file-conversion">ebook conversion guide</a>{" "}
        for the academic workflow.
      </li>
      <li>
        <strong>Forms:</strong> form fields don&rsquo;t round-trip well. Adobe
        Acrobat Pro is the only reliable option here.
      </li>
    </ul>
    <p>
      The honest take: if your PDF has complex structure and you need editable
      output, plan to pay for Adobe Acrobat Pro for that specific task. The free
      paths get you 80% there for simple documents, less for complex ones.
    </p>

    <h2 id="editable">Quick fix: making PDF text editable</h2>
    <p>
      The simplest workflow when you just need to edit some text in a PDF:
    </p>
    <ol>
      <li>
        Open the PDF in your browser (Chrome, Edge, Safari all have built-in
        PDF readers).
      </li>
      <li>
        Find a free PDF editor like Sejda free tier (3 docs / hour limit) or
        PDFescape free.
      </li>
      <li>
        For more substantial editing, convert to Word or Google Docs (paths
        above), edit, then export back to PDF.
      </li>
      <li>
        For form fields and signatures: install Adobe Acrobat Reader (free) for
        signing, Acrobat Pro ($20/month) for full editing.
      </li>
    </ol>
    <p>
      For non-sensitive PDFs, the upload-edit-download flow is fine. For
      sensitive content, prefer the convert-to-Word locally → edit → re-export
      flow.
    </p>

    <h2 id="tools">Recommended tools per scenario</h2>
    <table>
      <thead>
        <tr>
          <th>Scenario</th>
          <th>Best free option</th>
          <th>When to pay</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Text-based PDF, simple layout</td>
          <td>Word File → Open, or Google Docs</td>
          <td>Rarely needed</td>
        </tr>
        <tr>
          <td>Text-based PDF, sensitive content</td>
          <td><a href="/tools/pdf-to-text">Our PDF to text</a> + paste to Word</td>
          <td>Adobe Acrobat Pro for batch</td>
        </tr>
        <tr>
          <td>Scanned PDF (machine print)</td>
          <td><a href="/tools/pdf-ocr-to-text">Our PDF OCR</a></td>
          <td>ABBYY for accuracy on tables</td>
        </tr>
        <tr>
          <td>Handwritten PDF</td>
          <td><a href="/tools/pdf-ocr-to-text">Our PDF OCR</a> (50-90% depending on writing)</td>
          <td>ABBYY (specialized handwriting models)</td>
        </tr>
        <tr>
          <td>Complex tables / forms</td>
          <td>None reliable — plan to clean up</td>
          <td>ABBYY FineReader or Adobe Acrobat Pro</td>
        </tr>
        <tr>
          <td>Scientific paper with math</td>
          <td>Calibre (PDF → EPUB) preserves rendered math</td>
          <td>Mathpix for editable LaTeX</td>
        </tr>
      </tbody>
    </table>
  </>
);

export const cta = {
  label: "OCR a scanned PDF (browser-only, free)",
  targetSlug: "pdf-ocr-to-text",
};

export const faq = [
  {
    q: "How do I convert PDF to Word in 30 seconds?",
    a: "If the PDF is text-based (highlightable text), open it in Microsoft Word (File → Open) or Google Docs (upload + Open with Google Docs). Both auto-convert to editable. For sensitive documents, use our PDF to text tool and paste into Word — loses formatting but stays private.",
  },
  {
    q: "How do I convert a scanned or handwritten PDF to searchable text?",
    a: "OCR (optical character recognition) is required. Our PDF OCR tool runs Tesseract in your browser — no upload, supports 6 languages, 85-95% accuracy on print, 50-90% on handwriting. For better accuracy on complex layouts, ABBYY FineReader (paid) or Adobe Acrobat Pro is best.",
  },
  {
    q: "How do I make PDF text editable?",
    a: "Three paths: (1) Convert to Word/Google Docs and edit there, (2) Use a free PDF editor like Sejda or PDFescape (limited free tier), (3) Adobe Acrobat Pro ($20/month) for full editing including form fields and signatures. For sensitive PDFs, prefer the local convert-edit-re-export flow.",
  },
  {
    q: "Why do complex PDFs convert badly?",
    a: "Tables get flattened into space-separated text. Multi-column layouts get interleaved. Math symbols come out garbled. Forms don't round-trip. Plan for cleanup time, or use ABBYY FineReader / Adobe Acrobat Pro for one-shot complex conversions where layout fidelity matters.",
  },
];
